# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83abe83f3d13e6e6429a460aa2ffcdcfe4cbf492e12eb96ca6de29bb40b71654bc4b21f11a324ddd2756b9f3e0b9b0454088f3ed75d968df1ea4a45e3181ae87

test:
  secret_key_base: fd5cccec279648abaab65a59a23bdaebede4c6a76d0897fbffd23680db3f65740813452a1c128d94ed091b609ff648d0c2374751df529d9e0f26d374824186e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
